# -*- coding: utf-8 -*-
"""Chat with Your PDF (RAG + LangChain + Gradio) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAS7YUcMTuzb8R6JYUP0GHBHcX_lCZHe

## **STEP 1 — Install All Required Dependencies** ##

###
 - langchain-core / langchain-community: core components and integrations.

 - langchain-huggingface: connects Hugging Face pipelines to LangChain.

 - faiss-cpu: vector database for semantic search.

 - sentence-transformers: embedding models.

 - PyPDF2: for reading PDFs.

 - transformers / torch: for LLM models.

 - gradio: for building the interactive web interface.
"""


"""## **STEP 2 — Import Updated Libraries**"""

import gradio as gr
import PyPDF2 as pp
import torch
# LangChain modules
# ✅ Updated imports for new LangChain structure
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
# Hugging Face utilities
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

"""## **STEP 3 — PDF Text Extraction and Vector Database Creation**"""

def process_pdf(pdf_file):

  # blank string to hold extracted text
  text = " "

  # Use PyPDF2 to extract text from pdf pages
  reader = pp.PdfReader(pdf_file.name)
  for page in reader.pages:
    extracted = page.extract_text()
    if extracted and extracted.strip():
      text += extracted

  if not text:
    return None, None

  # Split text into smaller overlapping chunks
  splitter = RecursiveCharacterTextSplitter(
      chunk_size = 500,
      chunk_overlap = 50
  )
  chunks = splitter.split_text(text)

  # Create embeddings using a light model from Sentence-Transformers
  embedding_model = HuggingFaceEmbeddings(
      model_name = "sentence-transformers/all-MiniLM-L6-V2"
  )

  # Store embeddings in FAISS vector database
  vectorstore = FAISS.from_texts(chunks, embedding_model)

  return vectorstore, text

"""## **STEP 4 — Load the Local LLM (Hugging Face model)**"""

def load_llm():


  model_name = "distilgpt2"

  # Load the Tokenizer model
  tokenizer = AutoTokenizer.from_pretrained(model_name)
  model = AutoModelForCausalLM.from_pretrained(model_name)

  # Build a text-generation pipeline
  generator = pipeline(
      "text-generation",
      model = model,
      tokenizer = tokenizer,
      max_new_tokens = 128,
      temperature = 0.3,
      top_p = 0.8
  )

  # Wrap it in a LangChain LLM
  llm = HuggingFacePipeline(pipeline=generator)
  return llm

"""## **STEP 5 — Core RAG Query Function (Retrieval + Generation)**"""

# ------------------------------------------------------------
# ✅ Updated ask_question() function
# ------------------------------------------------------------
# ------------------------------------------------------------
# ✅ Updated and syntax-safe ask_question() function
# ------------------------------------------------------------
def ask_question(pdf_file, question):

  try:
    # if no file is uploaded, return a message
    if pdf_file is None:
      return "⚠️ Please upload a PDF file first."

    # 1️⃣ Build the vectorstore (extract text + embed)
    vectorstore, _ = process_pdf(pdf_file)
    retriever = vectorstore.as_retriever(search_kwargs={"k":3})

    # 2️⃣ Load the LLM
    llm = load_llm()

    # 3️⃣ Define the question-answering prompt
    prompt = PromptTemplate(

        input_variables = ["context", "question"],
        template = (

        """

        "Context:\n{context}\n\n"

        "Question: {question}\n\n"

        "Answer:"

        """
      )
    )

    # 4️⃣ Retrieve the most relevant text chunks
    docs = retriever.invoke(question)
    context = "\n".join([d.page_content for d in docs])

    # 5️⃣ Format the final prompt and generate answer
    formatted_output = prompt.format(context=context, question=question)
    output = llm.invoke(formatted_output) # Corrected typo: formatted_prompt -> formatted_output

    return output

  except Exception as e:
    return f"❌ Error: {str(e)}"



"""## **STEP 6 — Gradio User Interface (Frontend)**"""

with gr.Blocks(theme = gr.themes.Soft()) as rag_chatbot:
  # Title & Description
  gr.Markdown(
      """
      # 📘 Chat with Your PDF
      **Upload any PDF and ask questions about its content.**
      The model will retrieve relevant sections and answer contextually.
      """
  )

  # File upload row
  with gr.Row():
    pdf_file = gr.File(label = "📂 Upload a PDF", file_types=[".pdf"] )

  # User Input Row
  question = gr.Textbox(
        label = " 💬 Ask a Question ",
        placeholder = "e.g., What is the document about?",
        lines = 1
  )

  # Output field
  answer = gr.Textbox(
      label = "🤖 AI Answer",
      placeholder = "The model'response will appear here...",
      lines = 8,
      max_lines = 12,
      interactive=False
  )

  # Action Button
  submit_button = gr.Button("Ask")

  # Event : When the button is clicked -> Run the ask_question function
  submit_button.click(fn=ask_question, inputs=[pdf_file, question], outputs = answer)

"""## **STEP 7 — Launch the Gradio Interface**"""

if __name__ == "__main__":
    rag_chatbot.launch()


